# Generated by Django 3.1.5 on 2021-04-03 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('name', models.CharField(max_length=35)),
                ('usertype', models.CharField(choices=[('donor', 'donor'), ('reciepent', 'reciepent')], max_length=20)),
                ('email', models.EmailField(max_length=250, primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=12)),
                ('pincode', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=12)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=20)),
                ('allegeries', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=20)),
                ('cardiac_disease', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=20)),
                ('bleeding_disorder', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=20)),
                ('hiv', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
